### ISSUE TITLE
python3-urllib3 and python3-chardet missing from dependencies

### ISSUE THREAD

**Issue by irreleph4nt** [Kopano-dev/grapi#1]
5 days ago I have built grapi from source with all dependencies from requirements.txt installed in their most recent version available on Arch Linux, meeting or exceeding the minimum version requirements. Now that I wanted to test grapi, I see the following repeated multiple times in the journal when kopano-grapi.service is started:

```
kopano-grapi[4764]: /usr/lib/python3.7/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.2) or chardet (3.0.4) doesn't match a supported version!
``` 

It hence seems like chardet and urllib3 with a required version are missing from your .txt file.

**Comment by longsleep** [comment]
Grapi requirements.txt currently lists only direct dependencies. Not sure if that should be any different. If you use pip to install the dependencies from requirements it should take care of installing the dependency dependencies as well. What are your thoughts on this?

**Comment by irreleph4nt** [comment]
Hi,

Listing only direct dependencies is good and the tool apparently tells you when something is amiss at runtime, so all good.
I know this is a very unpopular opinion, especially in the Python community, but some Linux distributions like Arch heavily discourage the usage of tools like pip. The reason for this is that pip-installed software won't be owned by your distributions package manager, effectively existing outside of it's well maintained list of installed software. Think about it for a second: pacman tells me exactly what I have on my box and I can easily recreate that on a different PC. If I were to use tools like pip and its brethren, this becomes messy very quick and I am not even going into file permissions and the like. Users like me hence obtain their "modules" from the official distro repositories.

Looks like this is not for you to fix. If there is a practical way of listing more than just direct deps, that would make it easier on the user, though. I am closing this issue.

**Comment by longsleep** [comment]
Sure for packaging pip is not the way - one would have to package the direct grapi dependencies and their dependencies as well so that the dependency dependencies can be resolved with distro packaging tools.

Also for grapi packaging there only will be a direct dependency say for example on urllib3 if it is used directly by grapi code.

In any case, thanks for your feedback!
